#! /usr/bin/env Rscript
# vim: filetype=r:
#
# The MIT License (MIT)
#
# Copyright (c) 2013 Siraaj Khandkar
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

kDataDir <- ".git-analysis"
kAllDays  <- c("Sun", "Sat", "Fri", "Thu", "Wed", "Tue", "Mon")
kAllHours <- 0:23


cache <- list()


OperationBegin <- function(operation) {
  cache.name <- "operation.start.times"
  time.started <- proc.time()
  cache[[cache.name]][[operation]] <<- time.started
  msg <- sprintf("STARTED:\t%s", operation)
  write(msg, stderr())
}


OperationEnd <- function(operation) {
  cache.name <- "operation.start.times"
  time.started  <- cache[[cache.name]][[operation]]
  time.finished <- proc.time()
  time.delta    <- time.finished - time.started
  msg <- sprintf( "FINISHED:\t%s\nTIME ELAPSED:\t%f\n"
                , operation
                , time.delta["elapsed"]
                )
  write(msg, stderr())
}


ParseTimestamp <- function(timestamp) {
  # Example timestamp: "Tue Nov 6 21:28:48 2012 -0500"
  #
  # Using relative timestamps literally instead of converting with as.POSIXct,
  # because commits could've been made from several timezones, in which case I
  # think it is more interesting to see the time as perceived by the committer
  # rather than a globally normalized time.
  components <- unlist(strsplit(timestamp, " +"))
  day        <- components[1]
  time       <- components[4]
  time       <- unlist(strsplit(time, ":"))
  hour       <- as.numeric(time[1])

  list( day  = factor(day , levels = kAllDays)
      , hour = factor(hour, levels = kAllHours)
      , timestamp = as.POSIXct(timestamp, format="%a %b %d %T %Y %z")
      )
}


DashesToZeros <- function(v) {
  ifelse(v == "-", 0, v)
}


ParseCommit <- function(commit) {
  len <- length(commit)
  edits <- (
    if (len > 1) {
      edits <- commit[2:len]
      edits.indices.double.checked <- grep("^(\\d+|-)\t(\\d+|-)\t.+", edits)
      if (length(edits) == length(edits.indices.double.checked)) {
        edits
      } else {
        write("WARNING: some edit lines are in unexpected format.", stderr())
        edits[edits.indices.double.checked]
      }
    } else {
      vector()
    }
  )

  head <- unlist(strsplit(commit[1], "\\|"))

  timestamp <- head[1]
  timestamp <- ParseTimestamp(timestamp)
  name      <- head[2]
  hash      <- head[3]

  edits <- (
    if (length(edits) > 0)
      unlist(strsplit(edits, "\t"))
    else
      c(0, 0, "-")
  )
  edits <- matrix(edits, ncol=3, byrow=TRUE)

  list( hash           = hash
      , timestamp      = timestamp$timestamp
      , day            = timestamp$day
      , hour           = timestamp$hour
      , name           = name
      , num.files      = nrow(edits)
      , num.insertions = sum(as.numeric(DashesToZeros(edits[, 1])))
      , num.deletions  = sum(as.numeric(DashesToZeros(edits[, 2])))
      , edits          = edits
      )
}


ExtractCommits <- function(lines) {
  commit.start.indices <-
    grep("^[A-Z]{1}[a-z]{2} [A-Z]{1}[a-z]{2} \\d{1,2} \\d{2}:\\d{2}:\\d{2} \\d+ [+-]\\d{4}"
        , lines
        )
  commit.range.indices <- list()
  num.commits  <- length(commit.start.indices)
  num.lines <- length(lines)
  for (i in 1:num.commits) {
    range <- (
      if (i == num.commits) {
        commit.start.indices[i]:num.lines
      } else {
        commit.start.indices[i]:(commit.start.indices[i+1] - 1)
      }
    )
    commit.range.indices[[i]] <- range
  }
  lapply(commit.range.indices, function(indices) lines[indices])
}


ParseLog <- function(lines) {
  # Example log lines:
  #   Tue Nov 6 21:28:48 2012 -0500|Jeff Lebowski|550829ec241af50979f6a131dc864830681ac99d
  #   0\t3\tsrc/foo_bar.erl
  #   1\t4\tsrc/foo_baz.erl
  #   14\t15\tREADME.md
  #   Tue Nov 5 17:01:27 2012 -0700|Walter Sobchak|d140fd203486725c3eb377c43b7b5e9bb382d9cd
  #   -\t-\tbin/blob
  #   2\t4\tsrc/foo_year.erl
  operation <- "parse git commit log"
  OperationBegin(operation)
  commits.log <- lapply(ExtractCommits(lines), ParseCommit)
  OperationEnd(operation)
  commits.log
}


LookupEdits <- function(punchcard.row, edits.per.punch.hole) {
  punch.hole <- paste( c( punchcard.row["Day"]
                        , punchcard.row["Hour"]
                        , punchcard.row["Name"]
                        )
                     , collapse="-"
                     )
  edits <- edits.per.punch.hole[[punch.hole]]
  insertions <- edits$TotalInsertions
  deletions  <- edits$TotalDeletions
  c( ifelse(length(insertions) == 1, insertions, 0)
   , ifelse(length(deletions)  == 1, deletions,  0)
   )
}


PunchCard <- function(commits.tbl) {
  punchcard.tbl <- table(commits.tbl[, c("Day", "Hour", "Name")])
  punchcard.tbl <- as.data.frame(punchcard.tbl)

  operation <- "lookup edits per slot in punchard"
  OperationBegin(operation)
  edits.per.punch.hole <- EditsPerPunchHole(commits.tbl)
  edits <- apply(punchcard.tbl, 1, LookupEdits, edits.per.punch.hole)
  OperationEnd(operation)

  insertions <- edits[1, ]
  deletions  <- edits[2, ]

  punchcard.tbl$Diff  <- insertions - deletions
  punchcard.tbl$Edits <- insertions + deletions
  punchcard.tbl
}


PlotTimeline <- function(commits.tbl) {
  edit.types <- c("Insertion", "Deletion")

  insertions <- commits.tbl[, c("Timestamp", "TotalInsertions", "Name")]
  deletions  <- commits.tbl[, c("Timestamp", "TotalDeletions", "Name")]

  names(insertions) <- c("Timestamp", "ChangeVolume", "Name")
  names(deletions)  <- c("Timestamp", "ChangeVolume", "Name")

  insertions$ChangeType <- factor("Insertion", levels=edit.types)
  deletions$ChangeType  <- factor("Deletion" , levels=edit.types)

  deletions$ChangeVolume <- -(deletions$ChangeVolume)

  timeline.of.change.volumes <- rbind(insertions, deletions)

  # TODO: How to avoid the coercion of timestamps to ints?
  timeline.of.change.volumes$Timestamp <-
    as.POSIXct( timeline.of.change.volumes$Timestamp
              , origin="1970-01-01 00:00:00"
              )

  color.assignmnets <-
    c( "Insertion" = scales::muted("green")
     , "Deletion"  = scales::muted("red")
     )

  timeline <-
    ( ggplot2::ggplot(timeline.of.change.volumes)
    + ggplot2::aes( x     = Timestamp
                  , y     = ChangeVolume
                  , color = ChangeType
                  , fill  = ChangeType
                  )
    + ggplot2::geom_line()
    + ggplot2::scale_colour_manual(values=color.assignmnets)
    )
  list(change.volumes=timeline)
}


PlotDistributions <- function(commits.tbl, bin) {
  edit.types <- c("Insertion", "Deletion")
  insertions <- data.frame( Name     = commits.tbl$Name
                          , EditSize = commits.tbl$TotalInsertions
                          , EditType = factor("Insertion", levels=edit.types)
                          )
  deletions <- data.frame( Name     = commits.tbl$Name
                         , EditSize = commits.tbl$TotalDeletions
                         , EditType = factor("Deletion", levels=edit.types)
                         )
  color.assignmnets <-
    c( "Insertion" = scales::muted("green")
     , "Deletion"  = scales::muted("red")
     )
  distribution.edits.per.commit <-
    ( ggplot2::ggplot(rbind(deletions, insertions))
    + ggplot2::aes(x=EditSize, color=EditType, fill=EditType)
    + ggplot2::facet_wrap(~ Name, ncol=2, scales="free")
    + ggplot2::scale_fill_manual(values=color.assignmnets)
    + ggplot2::scale_colour_manual(values=color.assignmnets)
    )
  distribution.edits.per.commit.hist <-
    ( distribution.edits.per.commit
    + ggplot2::geom_histogram(binwidth=bin, alpha=0.4)
    )
  distribution.edits.per.commit.kde <-
    ( distribution.edits.per.commit
    + ggplot2::geom_density(binwidth=bin, alpha=0.4)
    )

  list( edits.per.commit.hist = distribution.edits.per.commit.hist
      , edits.per.commit.kde  = distribution.edits.per.commit.kde
      )
}


PlotPunchcards <- function(punchcard.tbl, punchcard.tbl.top.n) {
  axis <- ggplot2::aes(y=Day, x=Hour)
  geom <-
    list( ggplot2::geom_point(ggplot2::aes(size=Freq))
        , ggplot2::scale_size(range=c(0, 10))
        )
  facets.names <- ggplot2::facet_wrap(~ Name, ncol=1)
  color.edits <- ggplot2::aes(color=Edits)
  color.diff <-
      list( ggplot2::aes(color=Diff)
          , ggplot2::scale_colour_gradient2( low=scales::muted("red")
                                           , high=scales::muted("green")
                                           )
          )

  plot.all   <- ggplot2::ggplot(punchcard.tbl)
  plot.top.n <- ggplot2::ggplot(punchcard.tbl.top.n)

  plot.all   <- plot.all   + axis + geom
  plot.top.n <- plot.top.n + axis + geom + facets.names

  list( all                    = plot.all
      , all.edits              = plot.all   + color.edits
      , all.diff               = plot.all   + color.diff
      , top.n.committers       = plot.top.n
      , top.n.committers.edits = plot.top.n + color.edits
      , top.n.committers.diff  = plot.top.n + color.diff
      )
}


FetchLog <- function() {
  operation <- "fetch git commit log"
  OperationBegin(operation)
  command <- "git log --format='%ad|%an|%H' --numstat | grep -v '^$'"
  log <- system(command, intern=TRUE)
  OperationEnd(operation)
  log
}


FilePath <- function(type, name, format) {
  data.file.type   <- type
  data.file.name   <- name
  data.file.format <- format
  filename <- paste(data.file.type, data.file.name, sep="-")
  filename <- paste(filename, data.file.format, sep=".")
  file.path(kDataDir, filename)
}


StoreRaw <- function(lines, name) {
  file.path <- FilePath(type="raw", name=name, format="dat")
  file.path <- paste(file.path, "gz", sep=".")
  file <- gzfile(file.path, "wb", compression=9)
  writeLines(lines, file)
  close(file)
}


StoreTable <- function(data, name) {
  file.path <- FilePath(type="table", name=name, format="csv")
  file.path <- paste(file.path, "gz", sep=".")
  file <- gzfile(file.path, "wb", compression=9)
  write.csv( data
           , file      = file
           , row.names = FALSE
           )
  close(file)
}


StoreTableCommits <- function(df) {
  StoreTable(data=df, name="commits")
}


StoreTableEdits <- function(df) {
  StoreTable(data=df, name="edits")
}


StoreTablePunchcard <- function(df) {
  StoreTable(data=df, name="punchcard")
}


StorePlot <- function(plot, name) {
  filepath <- FilePath(type="plot", name=name, format="png")
  operation <- sprintf("storing plot: %s", filepath)
  OperationBegin(operation)
  ggplot2::ggsave( filename = filepath
                 , plot     = plot
                 , width    = 10
                 , height   = 5
                 )
  OperationEnd(operation)
}


StorePlotsTimeline <- function(plots) {
  plot.names <- names(plots)
  plot.names <- gsub("\\.", "-", plot.names)
  plot.names <- paste("timeline", plot.names, sep="-")
  len <- length(plots)
  if (len > 0) {
    for (i in 1:len) {
      StorePlot(plots[[i]], plot.names[i])
    }
  }
}


StorePlotsDistributions <- function(plots) {
  plot.names <- names(plots)
  plot.names <- gsub("\\.", "-", plot.names)
  plot.names <- paste("distribution", plot.names, sep="-")
  len <- length(plots)
  if (len > 0) {
    for (i in 1:len) {
      StorePlot(plots[[i]], plot.names[i])
    }
  }
}


StorePlotsPunchcard <- function(plots, n.committers) {
  plot.names <- names(plots)
  plot.names <- gsub("\\.", "-", plot.names)
  plot.names <- sub("-n-", sprintf("-%d-", n.committers), plot.names)
  plot.names <- paste("punchcard", plot.names, sep="-")
  len <- length(plots)
  if (len > 0) {
    for (i in 1:len) {
      StorePlot(plots[[i]], plot.names[i])
    }
  }
}


OptParse <- function() {
  options <-
    list( optparse::make_option( c("-n", "--n_top_committers")
                               , type    = "integer"
                               , default = 4
                               )
        , optparse::make_option( c("-b", "--bin_width")
                               , type    = "integer"
                               , default = 50
                               )
        )
  optparse::parse_args(optparse::OptionParser(option_list=options))
}


DoInit <- function() {
  options(warn=1)
  Sys.setlocale(locale="C")
  dir.create(kDataDir, showWarnings=FALSE)
}


ConstructTableOfEdits <- function(commits.log) {
  EditsOfCommit <- function(commit) {
    as.vector(t(cbind(commit$hash, commit$name, commit$edits)))
  }
  edits.vct <- unlist(lapply(commits.log, EditsOfCommit))
  edits.mtx <- matrix(edits.vct, ncol=5, byrow=TRUE)
  edits.tbl <- as.data.frame(edits.mtx, stringsAsFactors=FALSE)
  names(edits.tbl) <- c("Hash", "Name", "Insertions", "Deletions", "Filepath")
  edits.tbl$Insertions <- as.numeric(DashesToZeros(edits.tbl$Insertions))
  edits.tbl$Deletions  <- as.numeric(DashesToZeros(edits.tbl$Deletions))

  GetLast <- function(vct) vct[length(vct)]
  file.paths <- edits.tbl$Filepath
  file.names <- unlist(lapply(strsplit(file.paths, "/")  , GetLast))
  file.exts  <- unlist(lapply(strsplit(file.names, "\\."), GetLast))

  edits.tbl$FileExtension <- file.exts
  edits.tbl
}


ConstructTableOfCommits <- function(commits.log) {
  commits <- commits.log
  data.frame( Hash            = sapply(commits, function(c) c$hash )
            , Timestamp       = sapply(commits, function(c) c$timestamp )
            , Day             = sapply(commits, function(c) c$day )
            , Hour            = sapply(commits, function(c) c$hour )
            , Name            = sapply(commits, function(c) c$name )
            , TotalFiles      = sapply(commits, function(c) c$num.files )
            , TotalInsertions = sapply(commits, function(c) c$num.insertions )
            , TotalDeletions  = sapply(commits, function(c) c$num.deletions )

            , stringsAsFactors = FALSE
            )
}


EditsPerPunchHole <- function(commits.tbl) {
  edits.per.punch.hole <- list()
  for (i in 1:nrow(commits.tbl)) {
    row <- commits.tbl[i, ]
    row.insertions <- as.numeric(row["TotalInsertions"])
    row.deletions  <- as.numeric(row["TotalDeletions"])

    row.day.index  <- as.numeric(row["Day"])
    row.hour.index <- as.numeric(row["Hour"])

    row.day  <- kAllDays[row.day.index]
    row.hour <- kAllHours[row.hour.index]
    row.name <- row["Name"]

    punch.hole <- paste(c(row.day, row.hour, row.name), collapse="-")
    edits <- edits.per.punch.hole[[punch.hole]]

    insertions <- edits$TotalInsertions
    insertions <- if (is.null(insertions)) 0 else insertions
    deletions <- edits$TotalDeletions
    deletions <- if (is.null(deletions)) 0 else deletions

    edits$TotalInsertions <- (insertions + row.insertions)
    edits$TotalDeletions  <- (deletions + row.deletions)

    edits.per.punch.hole[[punch.hole]] <- edits
  }
  edits.per.punch.hole
}


GetTopCommitters <- function(commits.tbl, n=4) {
  names(sort(table(commits.tbl$Name), decreasing=TRUE))[1:n]
}


Main <- function() {
  DoInit()
  opt <- OptParse()

  log.lines <- FetchLog()
  StoreRaw(log.lines, "log")

  commits.log <- ParseLog(log.lines)
  edits.tbl <- ConstructTableOfEdits(commits.log)
  StoreTableEdits(edits.tbl)

  commits.tbl <- ConstructTableOfCommits(commits.log)
  StoreTableCommits(commits.tbl)

  timeline.plots <- PlotTimeline(commits.tbl)
  StorePlotsTimeline(timeline.plots)

  top.n.commiters <- GetTopCommitters(commits.tbl, opt$n_top_committers)

  punchcard.tbl       <- PunchCard(commits.tbl)
  punchcard.tbl.top.n <- punchcard.tbl[punchcard.tbl$Name %in% top.n.commiters, ]
  StoreTablePunchcard(punchcard.tbl)

  punchcard.plots <- PlotPunchcards(punchcard.tbl, punchcard.tbl.top.n)
  StorePlotsPunchcard(punchcard.plots, opt$n_top_committers)

  commits.tbl.top.n <- commits.tbl[commits.tbl$Name %in% top.n.commiters, ]
  plots.distributions <- PlotDistributions(commits.tbl.top.n, bin=opt$bin)
  StorePlotsDistributions(plots.distributions)
}


Main()
